### ISSUE TITLE
prosemirror-recreate-transform port?

### ISSUE THREAD

**Issue by mustafa0x** [fellowapp/prosemirror-py#287]
https://github.com/fellowapp/prosemirror-recreate-transform

> This module allows recreating the steps needed to go from document A to B should these not be available otherwise. Recreating steps can be interesting for example in order to show the changes between two document versions without having access to the original steps.

I'd like to do this on the backend. Is porting the plugin to python required?

Thanks!

**Comment by sciyoshi** [comment]
Yes, this is not something that's currently implemented for the Python side yet.

**Comment by mustafa0x** [comment]
Thanks for the reply @sciyoshi!

So if the client sends a new copy of "FooBar", and I want to store a transformation (or patch, in diff terms), so that the new copy can be reversed, the only solution is to use recreate-transform, correct?

- I could store the whole document, but that is inefficient for many edits.
- I could ask the client to calculate the transformation and send it, but the concern is the transformation can be tampered with. So if another user reverts, we won't get the original document.

**Comment by sciyoshi** [comment]
The preferred approach is to have the client send the steps required to transform the document, rather than the entire new document each time. Normally that's done by sending the Prosemirror steps directly, although they could also be generated with recreate-transform. I'm not sure what your exact situation is where there is a concern that transformations could be tampered with, but that approach in general should be the one that fits best with Prosemirror's design.

**Comment by mustafa0x** [comment]
Thanks again!

My primary concern is for deletes. If the transformation says "DELETE CHARS 1-10", it can't be undone unless chars 1-10 were stored. The backend must specify what chars 1-10 were, as the user could send any 10 chars.

Given the rudimentary structure below,

```js
// latest version of document
doc = {text: 'foo world'}

// list of all changes made
transactions = [
    // user creates document, writes "hello world"
    {id: 1, tx: [{op: 'add', pos: [1, 11], text: 'hello world'}]},

    // user deletes "hello "
    {id: 2, tx: [{op: 'delete', pos: [1, 5], text: 'hello '}]},

    // user writes "foo "
    {id: 3, tx: [{op: 'add', pos: [1, 4], text: 'foo '}]},
]
```

- If a user reverts the doc to transactions#2, the document becomes 'world'.
- If a user reverts the doc to transactions#1, the document becomes 'hello world'.
  - ⚠️ If the user who made transactions#2 told the backend that the text they deleted was in fact 'house ', the document would have become 'house world'.

There is an alternative solution. Don't include deleted text. When revering a document, start from the first transaction, replay them all until reaching the transaction the user wants to revert to. It can perform poorly for large documents that have many edits.

**Comment by sciyoshi** [comment]
I don't believe Prosemirror's deletion steps will include the deleted text. Those would normally be represented with [ReplaceStep](https://prosemirror.net/docs/ref/#transform.ReplaceStep)s which only have the range that is being removed.

The way we handle the issue is by occasionally storing snapshots of the document, so that the steps only need to be replayed from the latest snapshot.

**Comment by mustafa0x** [comment]
Thanks @sciyoshi, I greatly appreciate your input on this! :)
